### ISSUE TITLE
Reading of GHOST.EEA.hourly failed

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#138]
When colocating GHOST.hourly and EMEP using AerocomEvaluation the reading of GHOST failed.
The error happened right after reading data for more than one hour, so I am not able to easily debug this.
I think this failed because pyaerocom tried to write a cache file, but have no idea how the caching logic works.
@hansbrenna, have you encountered this before?

```
Running EMEP / GHOST.EEA.hourly (vmro3, vmro3)
100%|████████████████████████████████████████████████████████████████| 24/24 [1:20:53<00:00, 202.24s/it]^[[A
Failed to write cache
Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/io/cachehandler_ungridded.py", line 299, in write
    pickle.dump(data, out_handle, pickle.HIGHEST_PROTOCOL)
MemoryError
Failed to write to cache directory. Error: TypeError('remove: path should be string, bytes or os.PathLike, not method'). Deactivating caching in pyaerocom
Colocation between model EMEP / vmro3 and obs GHOST.EEA.hourly / vmro3 failed: Reason MemoryError((36053952, 12), dtype('float64'))
Failed to perform analysis: Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 926, in _run_gridded_ungridded
    resample_how=rshow)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation.py", line 567, in colocate_gridded_ungridded
    ungridded_data = ungridded_data.filter_by_meta(latitude=lat_range, longitude=lon_range)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 1567, in filter_by_meta
    new = self._new_from_meta_blocks(meta_matches, totnum_new)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 1575, in _new_from_meta_blocks
    new = UngriddedData(num_points=totnum_new)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 132, in __init__
    self._data = np.empty([num_points, self._COLNO]) * np.nan
MemoryError: Unable to allocate 3.22 GiB for an array with shape (36053952, 12) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 373, in run
    self.data[self.model_id] = self._run_gridded_ungridded(var_name)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 945, in _run_gridded_ungridded
    raise Exception(msg)
Exception: Colocation between model EMEP / vmro3 and obs GHOST.EEA.hourly / vmro3 failed: Reason MemoryError((36053952, 12), dtype('float64'))


Deactivating logging in Colocator. Reason: AttributeError("'NoneType' object has no attribute 'write'")
Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 926, in _run_gridded_ungridded
    resample_how=rshow)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation.py", line 567, in colocate_gridded_ungridded
    ungridded_data = ungridded_data.filter_by_meta(latitude=lat_range, longitude=lon_range)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 1567, in filter_by_meta
    new = self._new_from_meta_blocks(meta_matches, totnum_new)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 1575, in _new_from_meta_blocks
    new = UngriddedData(num_points=totnum_new)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 132, in __init__
    self._data = np.empty([num_points, self._COLNO]) * np.nan
MemoryError: Unable to allocate 3.22 GiB for an array with shape (36053952, 12) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 373, in run
    self.data[self.model_id] = self._run_gridded_ungridded(var_name)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 945, in _run_gridded_ungridded
    raise Exception(msg)
Exception: Colocation between model EMEP / vmro3 and obs GHOST.EEA.hourly / vmro3 failed: Reason MemoryError((36053952, 12), dtype('float64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cfg_ghost_emep.py", line 151, in <module>
    stp.run_evaluation()
  File "/home/eirikg/pyaerocom/pyaerocom/web/aerocom_evaluation.py", line 985, in run_evaluation
    col = self.run_colocation(model_name, obs_name, var_name)
  File "/home/eirikg/pyaerocom/pyaerocom/web/aerocom_evaluation.py", line 770, in run_colocation
    col.run(var_name)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 383, in run
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 926, in _run_gridded_ungridded
    resample_how=rshow)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation.py", line 567, in colocate_gridded_ungridded
    ungridded_data = ungridded_data.filter_by_meta(latitude=lat_range, longitude=lon_range)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 1567, in filter_by_meta
    new = self._new_from_meta_blocks(meta_matches, totnum_new)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 1575, in _new_from_meta_blocks
    new = UngriddedData(num_points=totnum_new)
  File "/home/eirikg/pyaerocom/pyaerocom/ungriddeddata.py", line 132, in __init__
    self._data = np.empty([num_points, self._COLNO]) * np.nan
MemoryError: Unable to allocate 3.22 GiB for an array with shape (36053952, 12) and data type float64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 373, in run
    self.data[self.model_id] = self._run_gridded_ungridded(var_name)
  File "/home/eirikg/pyaerocom/pyaerocom/colocation_auto.py", line 945, in _run_gridded_ungridded
    raise Exception(msg)
Exception: Colocation between model EMEP / vmro3 and obs GHOST.EEA.hourly / vmro3 failed: Reason MemoryError((36053952, 12), dtype('float64'))
```

**Comment by jgliss** [comment]
Hmm, seems indeed like there could not be enough memory allocated to pickle the `UngriddedData` object... are you running on lustre? Or on your local machine? If you are on lustre and the cache directory is in ~/MyPyaerocom/_cache you may not have enough quota...

You can check (and change) the cache directory, and / or activate / deactivate caching via:

```python
import pyaerocom as pya
print(pya.const.CACHEDIR)
# change 
pya.const.CACHEDIR = '/LotsOfSpace'
pya.const.CACHING = True  # False
```

Hope this helps somewhat...

**Comment by ejgal** [comment]
This is on lustre, cache directory is in home dir.
I tried to write a much larger file to the cache dir, and that worked, so this shouldn't be a storage issue.
There always seems to be at least 50-60 GB of free memory on the node.

Weird thing is that there is a file called `GHOST.EEA.hourly_vmro3.pkl` in MyPyaerocom/_cache, roughly 3.4 GB size and timestamped yesterday.

**Comment by hansbrenna** [comment]
Are you using the login node or a compute node? I use a compute node with 1 cpu and 30 GB RAM when I do this kind of precessing on PPI.

**Comment by ejgal** [comment]
This latest run showed that the process uses roughly 7% of the ram on lustre (8-9 GB) before the MemoryError. When the process tries to allocate memory for the ungriddedData object it wants to use additional 3.2 GB.

Managed to trigger a MemoryError in ipython on lustre by creating 4 arrays of 3.2 GB each (`np.empty([36053952, 12]) * np.nan`) so I guess there are some limits in place for each user or process even when the resources are not in use.
Will try to run it locally over the VPN instead.

**Comment by ejgal** [comment]
Oh, that explains it @hansbrenna! How do get a compute node?

**Comment by hansbrenna** [comment]
I use this command where I replace h_rt to the amount of wallclock time I need:

`qlogin -pe mpi 1 -q ded-parallelx.q -l h_vmem=30G -l h_rt=1:00:00`

**Comment by ejgal** [comment]
Ok. So running `python script.py` on the compute node would look something like this?
```
conda activate myenv
qlogin -pe mpi 1 -q ded-parallelx.q -l h_vmem=30G -l h_rt=1:00:00 python script.py
```
Or do I need to wrap everything in a bash script?

**Comment by hansbrenna** [comment]
This is for interactive running, so you would do qlogin to log into the compute node and, you get "normal" ssh shell, you activate your environment and cd to where you want to go and run the command manually. 

You can also submit scripts to the queue using qsub for batch processing. I haven't done that for now as I wanted the interactivity, but it should be relatively simple to set up a script.

**Comment by ejgal** [comment]
Okay, interactive running should be fine for this. Thanks!
Closing this for now.

**Comment by hansbrenna** [comment]
Most basic queue submission command I could find on PPI was `qsub -q ded-parallelx.q ./hello.sh`

I guess you could do: 

`qsub -pe mpi 1 -q ded-parallelx.q -l h_vmem=30G -l h_rt=1:00:00 /path/to/script/script.sh` 

where script.sh contains python script.py or you could add the hasbang #!/path/to/python to your python scripts.
