### ISSUE TITLE
EMEP Config Fails if `user_var_scale_colmap.ini` does not exist even though it is supposed to be optional according to the documentation

### ISSUE THREAD

**Issue by thorbjoernl** [metno/pyaerocom#1409]
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: 0.25.0.dev0
 - Computing platform: NA
 - Configuration file (if applicable): `emep/reporting_base.py` (modified)
 - Error message (if applicable): 

```
Traceback (most recent call last):
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/scripts/uemep_evaluation.py", line 25, in <module>
    res = ana.run()
          ^^^^^^^^^
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/experiment_processor.py", line 166, in run
    self.update_interface()
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/experiment_processor.py", line 180, in update_interface
    self.exp_output.update_interface()
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/experiment_output.py", line 214, in update_interface
    self._create_var_ranges_json()
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/experiment_output.py", line 562, in _create_var_ranges_json
    ranges[var] = self._get_cmap_info(var)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/experiment_output.py", line 537, in _get_cmap_info
    var_ranges_defaults = self.cfg.var_scale_colmap 
                          ^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/modules/rhel8/user-apps/fou-modules/python/python_3.11.3/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/setup_classes.py", line 395, in var_scale_colmap
    return VarWebScaleAndColormap(config_file=self.var_scale_colmap_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/thlun8736/python/pyaerocom/pyaerocom/aeroval/glob_defaults.py", line 47, in __init__
    raise FileNotFoundError(
FileNotFoundError: VarWebScaleAndColormap initialized with config_file: '/lustre/storeB/users/thlun8736/python/pyaerocom/user_var_scale_colmap.ini' which does not exist
```

**To Reproduce**
1. Run emep evaluation without `user_var_scale_colmap.ini` in current working directory.
2. Above error message

**Expected behavior**
Use default config instead, or docs should reflect that this file is necessary.

**Screenshots**

**Additional context**

**Comment by thorbjoernl** [comment]
Nevermind, it works if you remove the option in the config :man_facepalming:
