### ISSUE TITLE
Import pyaerocom locally inits wrongly when lustre is not mounted

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#23]
I work locally and have an empty mount /lustre in root directory. When trying to import pyaerocom in IPython console, I get the following error:
```
Initating pyaerocom configuration
Checking server configuration ...
Checking access to: /lustre/storeA
Process test:
Traceback (most recent call last):
  File "/home/hannas/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/hannas/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/storeA'
Access to lustre database: True
Init data paths for lustre
Expired time: 0.004 s
Supplementary data directory for etopo1 does not exist:
/lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/PYAEROCOM/topodata/etopo1/
```

**Comment by ejgal** [comment]
Could not reproduce the error running `import pyaerocom` in ipython while having an empty directory /lustre.
Please reopen with more details if this can be reproduced.
