### ISSUE TITLE
web resample_how as nested dict fails in main-dev

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#382]
After our last update using resample_how as a nested dictionary fails:

`resample_how={'vmro3' : {'daily' : {'hourly' : 'max'}}}`

fails. Traceback coming soon.

**Comment by jgliss** [comment]
Thanks, seems we are missing tests for that, we should add some tests for hourly data. I will create a synthetic hourly colocated data in _conftest_helpers.py which we can use for testing. This could also be used to test the code you wrote for processing of diurnal profiles.

**Comment by hansbrenna** [comment]
Traceback:

```
Colocation between model EMEP.cams61.BASE / vmro3 and obs GHOST.EBAS.hourly / vmro3 failed.
Traceback:
Traceback (most recent call last):
  File "/home/hansb/pyaerocom/pyaerocom/colocation_auto.py", line 999, in _run_gridded_ungridded
    model_data, obs_var)
  File "/home/hansb/pyaerocom/pyaerocom/colocation_auto.py", line 769, in _save_coldata
    coldata.to_netcdf(out_dir, savename=savename)
  File "/home/hansb/pyaerocom/pyaerocom/colocateddata.py", line 1135, in to_netcdf
    arr.to_netcdf(path=os.path.join(out_dir, savename), **kwargs)
  File "/home/hansb/miniconda3/envs/pya/lib/python3.7/site-packages/xarray/core/dataarray.py", line 2741, in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
  File "/home/hansb/miniconda3/envs/pya/lib/python3.7/site-packages/xarray/core/dataset.py", line 1699, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/home/hansb/miniconda3/envs/pya/lib/python3.7/site-packages/xarray/backends/api.py", line 1059, in to_netcdf
    _validate_attrs(dataset)
  File "/home/hansb/miniconda3/envs/pya/lib/python3.7/site-packages/xarray/backends/api.py", line 236, in _validate_attrs
    check_attr(k, v)
  File "/home/hansb/miniconda3/envs/pya/lib/python3.7/site-packages/xarray/backends/api.py", line 223, in check_attr
    f"Invalid value for attr {name!r}: {value!r} must be a number, "
TypeError: Invalid value for attr 'resample_how': {'daily': {'hourly': 'max'}} must be a number, a string, an ndarray or a list/tuple of numbers/strings for serialization to netCDF files
```

**Comment by jgliss** [comment]
From your traceback I see that it is when saving the colocated data, and that makes a lot of sense! I will work on a fix now.

**Comment by jgliss** [comment]
@hansbrenna actually, I am surprised that this only fails now,  because theroretically this should have failed already in the older versions...

**Comment by jgliss** [comment]
@hansbrenna I pushed something in #383 which should fix the issue hopefully (tested locally with synthetic colocated test data) and also added some related tests. Here, all works, can you check the PR? Cheers

**Comment by hansbrenna** [comment]
I'm closing this now.
