### ISSUE TITLE
aeroval: setting the min # of years for the trends makes the analysis crash

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#444]
I am trying to run the following aeroval 
[config file (metno internal!):](https://gitlab.met.no/aeroval/config/-/blob/griesie_dev/config_files/cfg_c3s_testing_cp.py)

it crashes with the following error message using main-dev @  commit c51049a6:
```  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
Traceback (most recent call last):
  File "/home/jang/data/aeroval-local-web/pyaerocom_config/config_files/cfg_c3s_testing_cp.py", line 272, in <module>
    res = ana.run()
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_processor.py", line 336, in run
    self._run_single_entry(model_name, obs_name, var_list)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_processor.py", line 285, in _run_single_entry
    self.make_json_files(files_to_convert)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_processor.py", line 105, in make_json_files
    self.coldata_to_json(file)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_processor.py", line 37, in coldata_to_json
    return engine.run(coldata)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/coldatatojson_engine.py", line 1413, in run
    hm_all = _process_heatmap_data(data, regnames, use_weights,
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/coldatatojson_engine.py", line 1064, in _process_heatmap_data
    subset_time_series = subset.get_regional_timeseries(regid)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/colocateddata.py", line 1796, in get_regional_timeseries
    result['obs'] = pd.Series(rgts.data[0], rgts.time)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/series.py", line 279, in __init__
    index = ensure_index(index)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5885, in ensure_index
    return Index(index_like, name=name, copy=copy)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 295, in __new__
    return _maybe_asobject(dtype, DatetimeIndex, data, copy, name, **kwargs)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6171, in _maybe_asobject
    return klass(data, dtype=dtype, copy=copy, name=name, **kwargs)
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 307, in __new__
    dtarr = DatetimeArray._from_sequence_not_strict(
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 326, in _from_sequence_not_strict
    subarr, tz, inferred_freq = sequence_to_dt64ns(
  File "/home/jang/anaconda.2018/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 2023, in sequence_to_dt64ns
    assert isinstance(result, np.ndarray), type(result)
AssertionError: <class 'xarray.core.dataarray.DataArray'>
```

removing the line 
 ```trends_min_yrs=3,``` 

makes it run

The config file is a bit messy, but I was chasing another error...

**Comment by jgriesfeller** [comment]
I added another config file for a satellite whose  time series is long enough [AATSR](https://gitlab.met.no/aeroval/config/-/blob/griesie_dev/config_files/cfg_c3s_AATSR.py)

The same crash happens there

**Comment by dulte** [comment]
I think this might be because get_regional_timeseries in colocationdata.py sends in DataArrays for xarray instead of numpy arrays. I can test this as soon as storeA is back up and I can access obs and mods

**Comment by jgliss** [comment]
I agree with @dulte, however, it is strange that it works in some cases, in any case, first thing to do is probably changing:

```python 
result['obs'] = pd.Series(rgts.data[0], rgts.time)
```
to 
```python
result['obs'] = pd.Series(rgts.data[0].data, rgts.time.data)
```

**Comment by jgriesfeller** [comment]
The error went away with the latest main-dev developments. Closing this issue.
