### ISSUE TITLE
aeroval: allow underscores in model names

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#472]
aeroval does like underscores in model names because it uses them to read information out of intermediate files using the underscore as a delimiter. Using such a common character is less than ideal.
So either use another character (e.g. @ ) or double characters or make the system smart enough to count the number of underscores from the end. 
Changing the model name in the visualizations does not always work:
in the config file:
```
MODELS = {
    'IFS-Reanalysis': dict(model_id='ECMWF_CAMS_REAN',
                         ),
    'GEOS-i33p2-v3-HIST': dict(model_id='GEOS-i33p2-v3_HIST',
                                )
}
```
I still get this at the end:
```
Processing: /home/jang/data/aeroval-local-web/coldata/aerocom/historical/GEOS-i33p2-v3-HIST/od550aer_od550aer_MOD-GEOS-i33p2-v3-HIST_REF-Aeronet_20000101_20201231_monthly_WORLD-wMOUNTAINS.nc
Computing json files for GEOS-i33p2-v3-HIST (od550aer) vs. Aeronet (od550aer)
Processing statistics timeseries for all regions
Processing heatmap data for all regions
Processing regional timeseries for all regions
Processing individual site timeseries data
Finished computing json files for GEOS-i33p2-v3-HIST (od550aer) vs. Aeronet (od550aer)
Time expired (TOTAL): 269.09 s
Traceback (most recent call last):
  File "/home/jang/data/aeroval-local-web/pyaerocom_config/config_files/cfg_aerocom_historical.py", line 182, in <module>
    res = ana.run()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_processor.py", line 122, in run
    self.update_interface()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_processor.py", line 134, in update_interface
    self.exp_output.update_interface()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_output.py", line 190, in update_interface
    self._create_var_ranges_json()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_output.py", line 455, in _create_var_ranges_json
    avail = self._results_summary()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_output.py", line 293, in _results_summary
    info = self._get_meta_from_map_files()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_output.py", line 435, in _get_meta_from_map_files
    tab.append(self._info_from_map_file(file))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pyaerocom-main-dev/lib/python3.9/site-packages/pyaerocom-0.12.0.dev2-py3.9.egg/pyaerocom/aeroval/experiment_output.py", line 275, in _info_from_map_file
    raise ValueError(f'invalid map filename: {filename}. Must '
ValueError: invalid map filename: /home/jang/data/aeroval-local-web/data/aerocom/historical/map/Aeronet-od550aer_Column_GEOS-i33p2-v3_HIST-od550aer.json. Must contain exactly 2 underscores _ to separate obsinfo, vertical and model info
```
Looking at the first and the last line of the error it seems that the map processing does not use the visualisation name at the model name in the intermediate file

**Comment by jgliss** [comment]
But I agree, that this should not crash but should just ignore that old file.
