### ISSUE TITLE
running aeroval concpm10 without setting variable based ranges crashes

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#501]
While running the aeroval analysis using the new config file format that @jgliss has introduced in pyaerocom 0.12.2 I tumble over some errors in the default config of pyerocom. As it is right now it seems to be mandatory to set variable ranges in the aeroval config file.
For instance using this:
```
MODEL_CFG = {
    'IFS-OSUITE': dict(model_id='ECMWF_OSUITE',
                       model_read_aux=MODEL_AUX_VARS,),
    'IFS-OSUITE-96h': dict(model_id='ECMWF_OSUITE_96H',
                           model_read_aux=MODEL_AUX_VARS),
} 
```
crashes here:
```
nit kg/m^3 in GriddedData sconcpm10 (ECMWF_OSUITE, freq=daily, unit=kg/m^3) is not AeroCom conform (ug m-3). Trying to convert ... 
Adding variable sconcpm10 in pyaerocom.const.VARS. since such a  variable is not defined in pyaerocom. Minimum and maximum values are added automatically based on value range in associated GriddedData object to: minimum=-300.0, maximum=6300.0. Since this will add the variable only temporarily during this run, this might interrupt the processing workflow unexpectedly when rerunning parts of the code without explictly calling GriddedData.register_var_glob. It may be best to add this variable to pyaerocom/data/variables.ini.
Traceback (most recent call last):
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/aeroval/modelmaps_engine.py", line 37, in run
    files = self._run_model(model, var_list)
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/aeroval/modelmaps_engine.py", line 78, in _run_model
    _files = self._process_map_var(model_name, var,
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/aeroval/modelmaps_engine.py", line 125, in _process_map_var
    varinfo = VarinfoWeb(var)
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/aeroval/varinfo_web.py", line 53, in __init__
    self.autofill_missing(vmin, vmax)
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/aeroval/varinfo_web.py", line 90, in autofill_missing
    self.cmap_bins = var.get_cmap_bins(infer_if_missing=True)
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/variable.py", line 462, in get_cmap_bins
    self._cmap_bins_from_vmin_vmax()
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/variable.py", line 434, in _cmap_bins_from_vmin_vmax
    raise AttributeError(f'need minimum and maximum to be specified '
AttributeError: need minimum and maximum to be specified for variable concpm10 in order to retrieve cmap_bins
python-BaseException
```
because `self.minimum == self.VMIN_DEFAULT` which is `VMIN_DEFAULT = -np.inf`

This then is due to the fact there's no minium set in 
https://github.com/metno/pyaerocom/blob/25aea64e95c027efb6e69bd0c3bbd5e76ef40231/pyaerocom/data/variables.ini#L2566-L2571

I think we should make sure to set defaults in a way that aeroval can be run with a minimum config file and with reasonable min and max parameters. This will also help to make different comparisons comparable, as in the old config file the limits for concpm10 were these:
```
'concpm10': [-1, 5000],  # ug m-3
```
I have the feeling though that the ranges in `variables.ini` were mainly used for plotting purposes, @jgliss?

**Comment by jgriesfeller** [comment]
adding a limit in `variables.ini` results in this message during aeroval processing:
```
WARNING: Found definition of outlier ranges for concpm10 (ECMWF_OSUITE) but outlier removal is deactivated. Consider checking your setup (note: model or obs outlier removal can be activated via attrs. model_remove_outliers and remove_outliers, respectively
```
For me this should not raise a Warning but just an information that the defaults were used.
If we don't want to use defaults, the aeroval setup should crash in `pyaerocom.aeroval.EvalSetup`.
The current behavior is not consistent.

**Comment by jgriesfeller** [comment]
I guess these problems arose because the example aeroval config file from where I started the setup had the following line in the configuration:
```
CFG['raise_exceptions'] = True
```
But the behavior described above is inconsistent anyway and should be corrected
