### ISSUE TITLE
aeroval output can't cope with variable aliases

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#516]
trying to run an aeroval analysis with models containing only the old aerocom `sconc*` variable names instead of the `conc*` names yields not output for the aeroval analysis.
I could trace it to this method:
https://github.com/metno/pyaerocom/blob/ac9978576c35316ee4224164e7ae1508bed475e8/pyaerocom/aeroval/experiment_output.py#L627

this code is missing a clause for the alias names:
https://github.com/metno/pyaerocom/blob/ac9978576c35316ee4224164e7ae1508bed475e8/pyaerocom/aeroval/experiment_output.py#L659-L682

the map directory contains these files, so the real name of the model variable is kept here:
```
AirNow-concpm10_Surface_IFS-OSUITE-sconcpm10.json
EEA-NRT-rural-concpm10_Surface_IFS-OSUITE-sconcpm10.json
MarcoPolo-concpm10_Surface_IFS-OSUITE-sconcpm10.json
```

**Comment by jgriesfeller** [comment]
Tried to solve that by renaming the variable via 
```
MODELS = {
    'IFS-OSUITE': dict(model_id='ECMWF_OSUITE',
                       model_read_aux=MODEL_AUX_VARS,
                       model_rename_vars={'sconcpm10': 'concpm10'}),
}
```
but the colocation cannot cope with that:
```
Deactivating file search by vertical code for ECMWF_OSUITE, since filenames do not include information about vertical code (probably AeroCom 2 convention)
Did not find concpm10 field but sconcpm10. Using the latter instead
Rearranging longitude dimension from 0 -> 360 definition to -180 -> 180 definition
Unit kg/m^3 in GriddedData sconcpm10 (ECMWF_OSUITE, freq=daily, unit=kg/m^3) is not AeroCom conform (ug m-3). Trying to convert ... 
The following variable combinations will be colocated
MODEL-VAR	OBS-VAR
concpm10	concpm10
Running ECMWF_OSUITE (concpm10) vs. EEAAQeRep.NRT (concpm10)
Renaming model variable from sconcpm10 to concpm10 in ColocatedData before saving to NetCDF.
Failed to perform analysis: Traceback (most recent call last):
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/colocation_auto.py", line 789, in run
    coldata = self._run_helper(mod_var, obs_var)
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/colocation_auto.py", line 1432, in _run_helper
    self._save_coldata(coldata)
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/colocation_auto.py", line 1263, in _save_coldata
    coldata.rename_variable(mod_var, mvar,
  File "/home/jang/data/Python3/pyaerocom_new/pyaerocom/colocateddata.py", line 1023, in rename_variable
    raise VarNotAvailableError('No such variable {} in ColocatedData'
pyaerocom.exceptions.VarNotAvailableError: No such variable sconcpm10 in ColocatedData

```
