### ISSUE TITLE
Confusing error message, when not connected to lustre

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#56]
Confusing errormessage. Its says it can access lustre but /lustre/storeA/ is not found.

```
Initating pyaerocom configuration
Checking database access...
Checking access to: /lustre/storeA
Process test:
Traceback (most recent call last):
  File "/home/hannas/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/hannas/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/storeA'
Access to lustre database: True
Init data paths for lustre
Expired time: 0.012 s
Supplementary data directory for etopo1 does not exist:
/lustre/storeA/project/aerocom/aerocom1/AEROCOM_OBSDATA/PYAEROCOM/topodata/etopo1/
```

**Comment by avaldebe** [comment]
as far as I can tel this is no longer a plroblem
