### ISSUE TITLE
Iris breaking CLI

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#747]
during testing of my parallelisation package, I saw this on feshly installed pyaerocom istallation from anaconda:
```python
(para_testing) jang@pc5378:~/.../Python3/pyaerocom-parallelization$ pya -h
Traceback (most recent call last):
  File "/home/jang/anaconda.2018/envs/para_testing/bin/pya", line 7, in <module>
    from pyaerocom.scripts.cli import main
  File "/home/jang/anaconda.2018/envs/para_testing/lib/python3.10/site-packages/pyaerocom/__init__.py", line 20, in <module>
    from . import geodesy
  File "/home/jang/anaconda.2018/envs/para_testing/lib/python3.10/site-packages/pyaerocom/geodesy.py", line 11, in <module>
    from pyaerocom.helpers import isnumeric
  File "/home/jang/anaconda.2018/envs/para_testing/lib/python3.10/site-packages/pyaerocom/helpers.py", line 31, in <module>
    STR_TO_IRIS = dict(count       = iris.analysis.COUNT,
AttributeError: module 'iris' has no attribute 'analysis'
```

For the moment just for documentation

**Comment by dulte** [comment]
This is iris' fault

**Comment by avaldebe** [comment]
this is reacted to #748
