### ISSUE TITLE
weird iris error in fresh installed anaconda install (iris 3.3.0 related?)

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#748]
For the moment just as documentation

checking 3.2.1 now
iris 3.3.1 was just released hours ago
```
Failed to convert to StationData Error: DataCoverageError("['od550gt1aer'] data could not be retrieved for meta index (or station name) [972.0]")
Extracting timeseries data from large array (shape: (5114, 180, 360)). This may take a while...
Failed to perform analysis: Traceback (most recent call last):
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/pyaerocom/colocation_auto.py", line 802, in run
    coldata = self._run_helper(mod_var, obs_var)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/pyaerocom/colocation_auto.py", line 1431, in _run_helper
    coldata = self._colocation_func(**args)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/pyaerocom/colocation.py", line 774, in colocate_gridded_ungridded
    grid_stat_data = data.to_time_series(longitude=ungridded_lons, latitude=ungridded_lats)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/pyaerocom/griddeddata.py", line 1161, in to_time_series
    result = self._to_time_series_xarray(scheme=scheme, add_meta=add_meta, **coords)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/pyaerocom/griddeddata.py", line 1221, in _to_time_series_xarray
    subset = subset.compute()
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/xarray/core/dataarray.py", line 993, in compute
    return new.load(**kwargs)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/xarray/core/dataarray.py", line 967, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/xarray/core/dataset.py", line 733, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/utils.py", line 71, in apply
    return func(*args, **kwargs)
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/dask/array/core.py", line 122, in getter
    c = a[b]
  File "/modules/centos7/user-apps/aerocom/anaconda3/envs/pya_para/lib/python3.9/site-packages/iris/fileformats/netcdf.py", line 477, in __getitem__
    dataset = netCDF4.Dataset(self.path)
  File "src/netCDF4/_netCDF4.pyx", line 2486, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2003, in netCDF4._netCDF4._get_vars
AttributeError: 'NoneType' object has no attribute 'dimensions'


Colocation processing status for IASI.ULB vs. AeronetSDAV3L2
     Model Var      Obs Var                     Status
0  od550gt1aer  od550gt1aer  NOT OK: Colocation failed
```

**Comment by jgriesfeller** [comment]
The same job using iris 3.2.1 worked normally. It seems we have to limit the iris version again.

**Comment by lewisblake** [comment]
Action item: have a closer look at the version of iris where this happens and them implement the limitation

**Comment by avaldebe** [comment]
we currently require iris 3.6.0 or better, so this is no longer relevant

https://github.com/metno/pyaerocom/blob/e0b14adf599620046faed94f5cecebe0d31c2753/pyproject.toml#L24

https://github.com/metno/pyaerocom/blob/e0b14adf599620046faed94f5cecebe0d31c2753/pyaerocom_env.yml#L6
