### ISSUE TITLE
Filtering on EEAAQeRep.v2 crashes on obs-only run when filtering by station_name

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#752]
In the obs-only run, there stations in 2016 in Turkey which report -9999.0 in their data (#751), and so need to be removed. In filtering out these stations, filtering by the `station_name` crashes the run, whereas filtering by the "station_id" works. This does not seem to be an issue for other observation networks.

Example of the filtering dictionary in the config file:
```python
EEA_RURAL_SITE_FILTER = dict(
    # Must filter by station_id not station_name here for some reason
    # station_name=["R350213", "R170313", "R100313", "R160613", "R570313", "R390213"],
    # negate="station_name",
    station_id=[
        "STA-TR570313",
        "STA-TR170313",
        "STA-TR160613",
        "STA-TR350213",
        "STA-TR100313",
        "STA-TR390213",
    ],
    negate="station_id",
)
```

Traceback:

```console
Colocation processing status for dummy vs. EEA-rural
  Model Var   Obs Var                     Status
0  concpm10  concpm10  NOT OK: Colocation failed
Traceback (most recent call last):
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 802, in run
    coldata = self._run_helper(mod_var, obs_var)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 1429, in _run_helper
    args = self._prepare_colocation_args(model_var, obs_var)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 1372, in _prepare_colocation_args
    obs_data = self.get_obs_data(obs_var)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 705, in get_obs_data
    return self._read_ungridded(obs_var)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 908, in _read_ungridded
    obs_data = obs_reader.read(
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/readungridded.py", line 673, in read
    self.read_dataset(
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/readungridded.py", line 448, in read_dataset
    data_out = data_out.apply_filters(**filters)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/ungriddeddata.py", line 1867, in apply_filters
    data = data.filter_by_meta(**filter_attributes)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/ungriddeddata.py", line 1951, in filter_by_meta
    new = self._new_from_meta_blocks(meta_matches, totnum_new)
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/ungriddeddata.py", line 1983, in _new_from_meta_blocks
    raise DataExtractionError("Filtering results in empty data object")
pyaerocom.exceptions.DataExtractionError: Filtering results in empty data object
```

**Comment by dulte** [comment]
I've starting looking into this. I'm running an evaluation now. Going to take some time do to the EEA reading...

**Comment by dulte** [comment]
Do you have a config I can look at?

**Comment by lewisblake** [comment]
/lustre/storeB/users/lewisb/Python/Evaluations/aeroval/config/config_files/cfg2_obs_only-copy.py

Please forgive the terrible naming convention

**Comment by dulte** [comment]
You have some station_id's and negate in your BASE_FILTER. Remove them and see if it still crashes
