### ISSUE TITLE
Add ICOS CO2 data

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#862]
We have been asked to add ICOS surface concentrations of CO2 into CAMS2_82. The data use the HARP-1.0 conventions, so we will likely be able to adapt/modify the MEP reader to read them in, but new a reader is expected to be needed. 

Example file:
```
netcdf icos-co2-nrt-zsf-3.0m-20230401-20230403T100002 {
dimensions:
	string_3 = 3 ;
	string_9 = 9 ;
	string_176 = 176 ;
	string_24 = 24 ;
	string_53 = 53 ;
	time = 24 ;
variables:
	char site_code(string_3) ;
	char site_name(string_9) ;
	char citation(string_176) ;
	char doi(string_24) ;
	char landing_page_url(string_53) ;
	double datetime_start(time) ;
		datetime_start:units = "days since 2000-01-01" ;
	double datetime_stop(time) ;
		datetime_stop:units = "days since 2000-01-01" ;
	float latitude ;
		latitude:units = "degree_north" ;
	float longitude ;
		longitude:units = "degree_east" ;
	float surface_altitude ;
		surface_altitude:units = "m" ;
	float altitude ;
		altitude:units = "m" ;
	double CO2_volume_mixing_ratio(time) ;
		CO2_volume_mixing_ratio:units = "ppm" ;

// global attributes:
		:Conventions = "HARP-1.0" ;
		:datetime_start = 8491. ;
		:datetime_stop = 8492. ;
		:source_product = "ICOS_ATC_NRT_ZSF_2022-03-01_2023-04-01_3.0_880-1167.CO2" ;
		:history = "2023-04-03T08:00:02Z harpicos \'ICOS_ATC_NRT_ZSF_2022-03-01_2023-04-01_3.0_880-1167.CO2\'" ;
}
```

Will add the [pyaerocom-preproc](https://github.com/metno/pyaerocom-preproc) results once ready.

**Comment by lewisblake** [comment]
Currently pyaerocom-preproc fails for the following reason.

```
pya-pp report-obs icos-co2 ./*.nc
Traceback (most recent call last):
  ...
  File "/home/lewisb/.local/pipx/venvs/pyaerocom-preproc/lib/python3.10/site-packages/pyaerocom_preproc/check_obs.py", line 128, in time_checker
    if (freq := infer_freq(datetime_stop - datetime_start)) == "?":

  File "/home/lewisb/.local/pipx/venvs/pyaerocom-preproc/lib/python3.10/site-packages/pyaerocom_preproc/check_obs.py", line 145, in infer_freq
    if np.unique(time_delta.dt.seconds) == [3600]:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Checking...

```[python]
>>> import xarray
>>> import numpy as np
>>> ds = xarray.open_dataset("icos-co2-nrt-zsf-3.0m-20230401-20230403T100002.nc")
>>> start = ds.get("datetime_start")
>>> stop = ds.get("datetime_stop")
>>> time_delta=stop-start
>>> np.unique(time_delta.dt.seconds)
array([3599, 3600])
```

Sp basically rounding errors in the representation of time in nanoseconds since 2000-01-01 lead to the checks not going through. @avaldebe do you think I should open and issue over in pyaerocom-preproc?

**Comment by lewisblake** [comment]
Update on the status of these data

```console
lewisb@pc5654:~/Documents/CAMS2_82/Co2Data/04/01$ pya-pp report-obs icos-co2 ./*.nc
icos-co2-nrt-bir-10.0m-20230401-20230403T100446.nc - time_checker - not a full year
icos-co2-nrt-bir-10.0m-20230401-20230403T100446.nc - data_checker - missing obs found
...
```

**Comment by lewisblake** [comment]
missing obs: name of internal variable is not the same as as original MEP data. variable name not recognized.

not full year: concated in the data with cdo.

potential solution: make MEP a base class and put specifics in there
