### ISSUE TITLE
AirNow reader crashing

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#890]
```console
The following variable combinations will be colocated
MODEL-VAR       OBS-VAR
concpm10        concpm10
Running ECMWF_ESUITE (concpm10) vs. AirNow (concpm10)
Cache file does not exist: /lustre/storeB/project/aerocom/aerocom2/pyaerocom_out/_cache/lewisb/AirNow_concpm10.pkl
Read AirNow data file(s)
 20%|██████████████████████████████████████████████                                                                                                                                                                                             | 22403/114286 [15:44<1:04:32, 23.73it/s]
Failed to perform analysis: Traceback (most recent call last):
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 802, in run
    coldata = self._run_helper(mod_var, obs_var)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 1429, in _run_helper
    args = self._prepare_colocation_args(model_var, obs_var)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 1372, in _prepare_colocation_args
    obs_data = self.get_obs_data(obs_var)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 705, in get_obs_data
    return self._read_ungridded(obs_var)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/colocation_auto.py", line 908, in _read_ungridded
    obs_data = obs_reader.read(
               ^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/readungridded.py", line 645, in read
    self.read_dataset(
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/readungridded.py", line 389, in read_dataset
    data_read = reader.read(vars_to_read, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/read_airnow.py", line 442, in read
    stats = self._read_files(files, vars_to_retrieve)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/read_airnow.py", line 316, in _read_files
    filedata = self._read_file(fp)
               ^^^^^^^^^^^^^^^^^^^
  File "/lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/read_airnow.py", line 283, in _read_file
    df = pd.read_csv(file, sep=self.FILE_COL_DELIM, names=self.FILE_COL_NAMES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lewisb/miniconda3/envs/pya/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 737, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1965, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2585: invalid start byte
```

**Comment by lewisblake** [comment]
A problem file: `/lustre/storeB/project/aerocom/aerocom1/AEROCOM_OBSDATA/MACC_INSITU_AirNow/201209/2012091920.dat`

**Comment by jgriesfeller** [comment]
Looking at the file with gvim:
![image](https://github.com/metno/pyaerocom/assets/10772065/aec1a782-4e95-4a8e-a419-a7937e088e37)

It's non UTF French characters, so the basic problem is that pandas (the file is read with `pandas.read_csv`) assumes the file is UTF-8 encoded which it is not.
Testing some solutions I have in my head that do not need a file conversion.

**Comment by lewisblake** [comment]
I tried all of the pandas encoding arguments. some work but then the code crashes later [here](https://github.com/metno/pyaerocom/blob/2104317f317f13006e6a6ecd4fd19c5223c2e888/pyaerocom/io/read_airnow.py#L385)

**Comment by jgriesfeller** [comment]
The station names use a French Canadian DOS code page `cp863` that is quite unusual these days. Although Python and pandas support that, pandas `read_csv` crashes later here:
```
File "/home/jang/mambaforge/envs/pyadev-applied/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 940, saw 2
```
It seems pandas is not widely tested with non UTF encoded files...
Trying to find an iconv line to convert to UTF-8.
Alternative is then to read the file by hand where one has more control...

**Comment by jgriesfeller** [comment]
Just for the record, the following works without problems:
```
with open(file, encoding="cp863") as f:
    data=f.readlines()
```
outcome:
```
>>> data[33]
'09/19/12|20:00|000050121|PARC OCÉANIE|-5|OZONE|PPB|32|Meteorological Service of Canada\n'
```

WTF is cp863 used in this data?

**Comment by lewisblake** [comment]
Does it work for the rest of the pipeline or just reading in the data?

**Comment by lewisblake** [comment]
FYI, after `encoding="cp863"` attempt there are other files which are not covered by this encoding
```console
Read AirNow data file(s)
 48%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                             | 54564/114286 [31:05<35:53, 27.74it/s]> /lustre/storeB/users/lewisb/Python/Evaluations/pyaerocom/pyaerocom/io/read_airnow.py(293)_read_file()
-> return df
(Pdb) file
'/lustre/storeB/project/aerocom/aerocom1/AEROCOM_OBSDATA/MACC_INSITU_AirNow/201606/2016060113.dat'
```

**Comment by lewisblake** [comment]
Since its inception the AirNow reader has used `pandas.read_csv()` https://github.com/metno/pyaerocom/blob/154662e4771b1d866be8776b6f664b7571e13b55/pyaerocom/io/read_airnow.py

So this is a new behavior

**Comment by jgriesfeller** [comment]
I don't think reading all the data with ASCII code page 863 is the solution. We will need to be able to apply the code page on a line by line basis using `cp863` only when `utf8` fails.
Taking over this work since @lewisblake is on holiday for 3 weeks...

**Comment by jgriesfeller** [comment]
Trying a similar solution as here: https://stackoverflow.com/questions/44402983/how-to-read-the-file-without-encoding-and-extract-desired-urls-with-python3

**Comment by jgriesfeller** [comment]
Trying another approach by determining the encoding first using the linked code (with the small modification that we try `cp863` right after `utf_8`) and tell pandas to use that encoding...

**Comment by jgriesfeller** [comment]
providing pandas with the right encoding actually works. But `pandas.read_csv` is not really quite slow...

and btw there's malformed data lines in the data as well (too many rows)
